title: How to activate Aká.ms/mfásetúp
description: Aká.ms/mfásetúp - (MFA) is a security level that verifies a user's identity by requiring multiple layers of authentication.Enable Microsoft multi-factor authentication to ramp up business security.
